# Generated by Django 4.2.3 on 2023-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpiece",
            name="firebase_image_url",
            field=models.URLField(blank=True),
        ),
    ]
