# Generated by Django 4.2.3 on 2023-07-24 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_alter_artpiece_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artpiece",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
