# Generated by Django 4.2.3 on 2023-07-25 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0005_alter_artpiece_options_alter_gallery_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="city",
        ),
    ]
